version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - mynetwork

volumes:
  db:
networks:
  mynetwork:
